apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ghost-deploy1
  name: ghost-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost-deploy1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghost-deploy1
    spec:
      containers:
      - image: ghost
        name: ghost
        ports:
        - containerPort: 80
        resources: {}
status: {}
