apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ghost-deploy
  name: ghost-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghost-deploy
    spec:
      containers:
      - image: ghost
        name: ghost
        ports:
        - containerPort: 80
        resources: {}
status: {}
