apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ghost-deploy
  name: ghost-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
